/**
 * Timetable Model
 * Represents generated academic timetables with entries
 * @module models/timetable
 */

import { Document, Schema, model, Types } from 'mongoose';

/**
 * Timetable status enumeration
 */
export enum TimetableStatus {
  DRAFT = 'draft',
  GENERATED = 'generated',
  PUBLISHED = 'published',
}

/**
 * Day of week enumeration
 */
export enum DayOfWeek {
  MONDAY = 'Monday',
  TUESDAY = 'Tuesday',
  WEDNESDAY = 'Wednesday',
  THURSDAY = 'Thursday',
  FRIDAY = 'Friday',
  SATURDAY = 'Saturday',
}

/**
 * Timetable Entry interface
 * Represents a single class schedule entry
 */
export interface ITimetableEntry {
  day: DayOfWeek;
  period: number;
  subject: Types.ObjectId;
  faculty: Types.ObjectId;
  classroom: Types.ObjectId;
  startTime: string;
  endTime: string;
}

/**
 * Timetable interface
 * Extends Mongoose Document for type safety
 */
export interface ITimetable extends Document {
  department: Types.ObjectId;
  semester: number;
  academicYear: string;
  generatedBy: Types.ObjectId;
  generatedAt: Date;
  status: TimetableStatus;
  timetableEntries: ITimetableEntry[];
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Timetable Entry Schema
 * Subdocument schema for individual schedule entries
 */
const timetableEntrySchema = new Schema<ITimetableEntry>(
  {
    day: {
      type: String,
      enum: {
        values: Object.values(DayOfWeek),
        message: `Day must be one of: ${Object.values(DayOfWeek).join(', ')}`,
      },
      required: [true, 'Day is required'],
    },
    period: {
      type: Number,
      required: [true, 'Period is required'],
      min: [1, 'Period must be at least 1'],
      max: [12, 'Period cannot exceed 12'],
    },
    subject: {
      type: Schema.Types.ObjectId,
      ref: 'Subject',
      required: [true, 'Subject reference is required'],
    },
    faculty: {
      type: Schema.Types.ObjectId,
      ref: 'Faculty',
      required: [true, 'Faculty reference is required'],
    },
    classroom: {
      type: Schema.Types.ObjectId,
      ref: 'Classroom',
      required: [true, 'Classroom reference is required'],
    },
    startTime: {
      type: String,
      required: [true, 'Start time is required'],
      match: [/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/, 'Invalid time format (HH:MM)'],
    },
    endTime: {
      type: String,
      required: [true, 'End time is required'],
      match: [/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/, 'Invalid time format (HH:MM)'],
    },
  },
  { _id: true }
);

/**
 * Timetable Schema
 * Defines the structure and validation for timetable documents
 */
const timetableSchema = new Schema<ITimetable>(
  {
    department: {
      type: Schema.Types.ObjectId,
      ref: 'Department',
      required: [true, 'Department reference is required'],
    },
    semester: {
      type: Number,
      required: [true, 'Semester is required'],
      min: [1, 'Semester must be at least 1'],
      max: [8, 'Semester cannot exceed 8'],
    },
    academicYear: {
      type: String,
      required: [true, 'Academic year is required'],
      match: [
        /^\d{4}-\d{4}$/,
        'Academic year must be in format YYYY-YYYY (e.g., 2024-2025)',
      ],
    },
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by (user) reference is required'],
    },
    generatedAt: {
      type: Date,
      required: [true, 'Generation timestamp is required'],
      default: Date.now,
    },
    status: {
      type: String,
      enum: {
        values: Object.values(TimetableStatus),
        message: `Status must be one of: ${Object.values(TimetableStatus).join(', ')}`,
      },
      required: [true, 'Status is required'],
      default: TimetableStatus.DRAFT,
    },
    timetableEntries: [timetableEntrySchema],
  },
  {
    timestamps: true,
    collection: 'timetables',
  }
);

// Indexes for performance optimization
timetableSchema.index({ department: 1 });
timetableSchema.index({ semester: 1 });
timetableSchema.index({ academicYear: 1 });
timetableSchema.index({ generatedBy: 1 });
timetableSchema.index({ status: 1 });
timetableSchema.index({ department: 1, semester: 1, academicYear: 1 });
timetableSchema.index({ createdAt: -1 });

/**
 * Timetable Model
 */
export const Timetable = model<ITimetable>('Timetable', timetableSchema);
